"""empty message

Revision ID: d938082897ea
Revises: 488c96832db9
Create Date: 2022-08-25 22:34:39.143400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd938082897ea'
down_revision = '488c96832db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('reserved_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reserved_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period')
    # ### end Alembic commands ###
